### ISSUE TITLE
look into how to create a gem 

### ISSUE THREAD

**Issue by jenni** [berlindiamonds/discourse-sync-to-nextcloud#2]
Follow this guide that @elfenars recommended so in the future we can create a Nextcloud gem that wraps its API and use it in the plugin:

http://guides.rubygems.org/make-your-own-gem/

**Comment by jancborchardt** [comment]
Is the gem published anywhere by the way? We could tweet and spread the word if other Ruby devs want to use it. :)

**Comment by jenni** [comment]
Hi @jancborchardt , I've just reopened the issue because we didn't do the gem. 
It would be amazing to work on this nextcloud gem, but it'll have to be after the summer ends, I would really like to look into it :)
There's a gem called Ocman that works pretty good with webDAV and it's what we've used for this plugin. One thing missing from this gem is the possibility to delete files from the Trash folder without doing it from the interface (so basically, do a "delete forever").
I've seen some providers in Nextcloud don't offer much space and if things pile up in the trash the general space narrows. It'll be nice to improve this, for example.
Anyways, we'll see each other here? https://www.meetup.com/es-ES/opensourceladies/events/242038340/
:)

**Comment by jancborchardt** [comment]
> I've seen some providers in Nextcloud don't offer much space and if things pile up in the trash the general space narrows. 

Actually, as space gets low, the trash is automatically and intelligently emptied. First versions of files are reduced, and then I think files by age. cc @schiessle for more info on that.

> Anyways, we'll see each other here? https://www.meetup.com/es-ES/opensourceladies/events/242038340/

Cool that you’ll be there – see you then! :)
